// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates outbreak advisories based on reported symptoms and water source data.
 *
 * - generateOutbreakAdvisory - A function that generates outbreak advisories.
 * - GenerateOutbreakAdvisoryInput - The input type for the generateOutbreakAdvisory function.
 * - GenerateOutbreakAdvisoryOutput - The return type for the generateOutbreakAdvisory function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateOutbreakAdvisoryInputSchema = z.object({
  symptomsData: z
    .string()
    .describe('A summary of reported symptoms including type, severity, and duration.'),
  waterSourceData: z
    .string()
    .describe('A summary of water source data including location, visual inspection notes, and photos.'),
  location: z.string().describe('The GPS coordinates of the affected area.'),
});

export type GenerateOutbreakAdvisoryInput = z.infer<
  typeof GenerateOutbreakAdvisoryInputSchema
>;

const GenerateOutbreakAdvisoryOutputSchema = z.object({
  advisoryTitle: z.string().describe('The title of the outbreak advisory.'),
  advisorySummary: z.string().describe('A summary of the outbreak advisory.'),
  affectedArea: z.string().describe('The affected geographical area.'),
  recommendedActions: z
    .array(z.string())
    .describe('A list of recommended actions for the public.'),
});

export type GenerateOutbreakAdvisoryOutput = z.infer<
  typeof GenerateOutbreakAdvisoryOutputSchema
>;

export async function generateOutbreakAdvisory(
  input: GenerateOutbreakAdvisoryInput
): Promise<GenerateOutbreakAdvisoryOutput> {
  return generateOutbreakAdvisoryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateOutbreakAdvisoryPrompt',
  input: {schema: GenerateOutbreakAdvisoryInputSchema},
  output: {schema: GenerateOutbreakAdvisoryOutputSchema},
  prompt: `You are a public health official responsible for generating outbreak advisories.

  Based on the reported symptoms, water source data, and location, create a concise and informative outbreak advisory for the public.

  Symptoms Data: {{{symptomsData}}}
  Water Source Data: {{{waterSourceData}}}
  Location: {{{location}}}

  Consider the following when generating the advisory:
  - The potential health risks associated with the reported symptoms and water source data.
  - The geographical area affected by the outbreak.
  - Recommended actions the public should take to protect themselves.

  Ensure the advisory is clear, actionable, and easy to understand.

  Output the advisory in the following JSON format:
  {
    "advisoryTitle": "The title of the outbreak advisory.",
    "advisorySummary": "A summary of the outbreak advisory.",
    "affectedArea": "The affected geographical area.",
    "recommendedActions": ["A list of recommended actions for the public."]
  }`,
});

const generateOutbreakAdvisoryFlow = ai.defineFlow(
  {
    name: 'generateOutbreakAdvisoryFlow',
    inputSchema: GenerateOutbreakAdvisoryInputSchema,
    outputSchema: GenerateOutbreakAdvisoryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
