// This is an autogenerated file from Firebase Studio.
import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { messages } = body;

    // Forward the request to the server-side API route
    const response = await fetch(new URL('/api/chat/server', req.url), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ messages }),
    });

    // Check if the response is valid
    if (!response.ok || !response.body) {
      const errorText = await response.text();
      console.error('Error from server-side chat API:', errorText);
      return NextResponse.json(
        { error: `Server-side API error: ${response.statusText}` },
        { status: response.status }
      );
    }
    
    // Return the streaming response
    return new NextResponse(response.body, {
      headers: {
        'Content-Type': 'text/plain',
      },
    });

  } catch (e) {
    console.error('Error in edge route:', e);
    return NextResponse.json(
      { error: 'Error processing chat request in edge route' },
      { status: 500 }
    );
  }
}
